services:
  - type: web
    name: cattle-erp
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT --workers 2
    pythonVersion: "3.11.4"
    autoDeploy: true
